config:
  project: gcp-demos-505417
  region: us-central1
  sharedStackName: alfredsyoung/gcp-demos-shared-infra
  websiteImageTag: 2608.20.0f89b9b-hotfix
  workerImageTag: 2608.20.0f89b9b-hotfix
  deletionProtection: false
  stripeSecretKeySecretVersion: 1
