config:
  project: gcp-demos-505417
  region: us-central1
  sharedStackName: alfredsyoung/gcp-demos-shared-infra
  websiteImageTag: 2609.09.f9255e5-hotfix
  rendererImageTag: 2609.09.f9255e5-hotfix
  deletionProtection: false
