config:
  project: gcp-demos-505417
  region: us-central1
  sharedStackName: alfredsyoung/gcp-demos-shared-infra
  websiteImageTag: 2608.27.09f5a3c-hotfix
  ghostImageTag: 2608.27.09f5a3c-hotfix
  ghostUrl: https://blog.alfredyoung.com
  ghostAdminUrl: https://ghost.alfredyoung.com
  deletionProtection: false
