import { redirect } from 'next/navigation'

import { CheckOrderStatusHandler } from '@org/pdf-shop-application'

import { PageShell, Card, Heading, Subheading } from '@/lib/ui'
import { pinoLogger } from '@/lib/pino'
import { documentIdSchema } from '@/lib/schemas'

import { DownloadStatusPoller } from './download-status-poller'

const handler = CheckOrderStatusHandler({
  dataRoot: process.env.DATA_ROOT ?? '',
  logger: pinoLogger,
})

export default async function DownloadPage({
  searchParams,
}: {
  searchParams: Promise<{ doc?: string }>
}) {
  const { doc: documentId } = await searchParams
  if (!documentId) {
    redirect('/create')
  }
  const parsed = documentIdSchema.safeParse({ documentId })

  let status: boolean | null = null
  if (parsed.success) {
    try {
      status = await handler(parsed.data)
    } catch (err) {
      pinoLogger.debug({ err }, 'Failed to check order status')
      status = null
    }
  }
  const ready = Boolean(status)

  return (
    <PageShell>
      <Card>
        <Heading>Your document</Heading>
        <Subheading>
          Payment received. Your document is being generated by our processing
          pipeline.
        </Subheading>
        <DownloadStatusPoller documentId={documentId} initialReady={ready} />
      </Card>
    </PageShell>
  )
}
