import { redirect } from 'next/navigation'

import { CheckOrderStatusHandler } from '@org/pdf-shop-application'

import { PageShell, Card, Heading, Subheading } from '@/lib/ui'
import { StepIndicator } from '@/lib/StepIndicator'
import { pinoLogger } from '@/lib/pino'
import { resolveDataRoot } from '@/lib/dataRoot'
import { documentIdSchema } from '@/lib/schemas'

import { DownloadStatusPoller } from './download-status-poller'

export default async function DownloadPage({
  searchParams,
}: {
  searchParams: Promise<{ doc?: string }>
}) {
  const { doc: documentId } = await searchParams
  if (!documentId) {
    redirect('/create')
  }
  const parsed = documentIdSchema.safeParse({ documentId })

  let status: { paid: boolean; generated: boolean } | null = null
  if (parsed.success) {
    const handler = CheckOrderStatusHandler({
      dataRoot: resolveDataRoot(),
      logger: pinoLogger,
    })
    try {
      status = await handler(parsed.data)
    } catch (err) {
      pinoLogger.debug({ err }, 'Failed to check order status')
      status = null
    }
  } else {
    pinoLogger.warn({ err: parsed.error }, 'Invalid document id')
  }
  const ready = Boolean(status?.paid && status?.generated)

  return (
    <PageShell>
      <StepIndicator currentStep="download" />
      <Card>
        <Heading>Your document</Heading>
        <Subheading>
          Payment received. Your document is being generated by our processing
          pipeline.
        </Subheading>
        <DownloadStatusPoller documentId={documentId} initialReady={ready} />
      </Card>
    </PageShell>
  )
}
