import { redirect } from 'next/navigation'
import { PageShell, Card, Heading, Subheading } from '@/lib/shared/ui'
import { getGeneratedDocument } from '@/lib/documents/DocumentGenerated.server'
import { DownloadStatusPoller } from './download-status-poller'

export default async function DownloadPage({
  searchParams,
}: {
  searchParams: Promise<{ documentId?: string }>
}) {
  const { documentId } = await searchParams
  if (!documentId) {
    redirect('/spec')
  }
  let status: any
  try {
    status = await getGeneratedDocument({ documentId })
  } catch (err) {
    console.warn(err)
    status = null
  }
  const ready = Boolean(status)

  return (
    <PageShell>
      <Card>
        <Heading>Your document</Heading>
        <Subheading>
          Payment received. Your document is being generated by our processing
          pipeline.
        </Subheading>
        <DownloadStatusPoller documentId={documentId} initialReady={ready} />
      </Card>
    </PageShell>
  )
}
