import {
  Document,
  Page,
  View,
  Text,
  Link,
  StyleSheet,
} from '@react-pdf/renderer'

const PAGE_MARGIN = 40
const HEADER_HEIGHT = 50
const FOOTER_HEIGHT = 60

const makeStyles = (colorScheme: 'light' | 'dark') => {
  const isDark = colorScheme === 'dark'
  const background = isDark ? '#111827' : '#ffffff'
  const text = isDark ? '#f9fafb' : '#111827'
  const muted = isDark ? '#9ca3af' : '#6b7280'
  const divider = isDark ? '#374151' : '#e5e7eb'
  const accent = isDark ? '#818cf8' : '#4f46e5'

  return StyleSheet.create({
    page: {
      backgroundColor: background,
      color: text,
      paddingTop: HEADER_HEIGHT + PAGE_MARGIN,
      paddingBottom: FOOTER_HEIGHT + PAGE_MARGIN,
      paddingHorizontal: PAGE_MARGIN,
      fontSize: 12,
    },
    header: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: HEADER_HEIGHT,
      paddingHorizontal: PAGE_MARGIN,
      justifyContent: 'center',
      borderBottomWidth: 1,
      borderBottomColor: divider,
    },
    headerText: { fontSize: 11, fontWeight: 700, color: accent },
    title: { fontSize: 22, fontWeight: 700, marginBottom: 12 },
    divider: {
      borderBottomWidth: 1,
      borderBottomColor: divider,
      marginBottom: 16,
    },
    body: { fontSize: 12, lineHeight: 1.6 },
    footer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: FOOTER_HEIGHT,
      paddingHorizontal: PAGE_MARGIN,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: divider,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    footerText: { fontSize: 9, color: muted },
    footerLink: { fontSize: 9, color: accent, textDecoration: 'none' },
  })
}

export function DocumentPdf({
  colorScheme,
  title,
  body,
}: {
  colorScheme: 'light' | 'dark'
  title: string
  body: string
}) {
  const styles = makeStyles(colorScheme)
  const generatedAt = new Date().toLocaleString('en-US', {
    dateStyle: 'medium',
    timeStyle: 'short',
  })

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header} fixed>
          <Text style={styles.headerText}>PDF Shop</Text>
        </View>

        <Text style={styles.title}>{title}</Text>
        <View style={styles.divider} />
        <Text style={styles.body}>{body}</Text>

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>
            Generated by a sample application ·{' '}
            <Link
              style={styles.footerLink}
              src="https://pdf-shop.alfredyoung.com"
            >
              pdf-shop.alfredyoung.com
            </Link>
          </Text>
          <Text style={styles.footerText}>{generatedAt}</Text>
        </View>
      </Page>
    </Document>
  )
}
